version: '3'

services:
  s3system:
    image: minio/minio:latest
    ports:
      - 9000:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3system.entrypoints=http"
      - "traefik.http.routers.s3system.rule=Host(`${GLEANER_OSS_DOMAIN}`)"
      - "traefik.http.middlewares.s3system-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.s3system.middlewares=s3system-https-redirect"
      - "traefik.http.routers.s3system-secure.entrypoints=https"
      - "traefik.http.routers.s3system-secure.rule=Host(`${GLEANER_OSS_DOMAIN}`)"
      - "traefik.http.routers.s3system-secure.tls=true"
      - "traefik.http.routers.s3system-secure.tls.certresolver=http"
      - "traefik.http.routers.s3system-secure.service=s3system"
      - "traefik.http.services.s3system.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik_default"
    volumes:
      - ${GLEANER_OBJECTS}:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - traefik_default
    command: ["server", "/data"]

  headless:
    image: chromedp/headless-shell:latest
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222
    networks:
      - traefik_default

networks:
  traefik_default:

